title: Samyak's Space!
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog"
url: "https://samyak-jn.github.io/"
site-twitter: https://twitter.com/samyak__jn

# Author Settings
author: Samyak Jain
author-img: samyak-jain.jpg 
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: samyak__jn
#social-facebook: # add your Facebook handle
social-github: samyak-jn
social-linkedin: samyak-jn
social-email: samyak.jn11@gmail.com

# Disqus
discus-identifier: samyak-jn

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
