title: Samyak's Space!
description: > # this means to ignore newlines until "baseurl:"
  The place where, I express and write.
permalink: ':title/'
#baseurl: "/blog"
url: "https://samyak-jn.tk/"
site-twitter: https://twitter.com/samyak__jn

# Author Settings
author: Samyak Jain
author-img: Samyak-1.jpeg 
about-author: A third-year, Under-Graduate student pursuing Computer Science and Engineering. A newbie in the field of open-source. Always hungry to keep learning. 
social-twitter: samyak__jn
#social-facebook: # add your Facebook handle
social-github: samyak-jn
social-linkedin: samyak-jn
social-email: samyak.jn11@gmail.com

# Disqus
#discus-identifier: samyak-jn

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
